import Vue from 'vue';
import Vuex from 'vuex';

Vue.use(Vuex);

export const store = new Vuex.Store({
  state: {
    currentTrack: {},
    tracklist: [
      {
      "kind": "track",
      "isPlaying": false,
      "id": 419605204,
      "created_at": "2018/03/25 18:01:10 +0000",
      "user_id": 277946511,
      "duration": 251372,
      "commentable": true,
      "state": "finished",
      "original_content_size": 5345986,
      "last_modified": "2018/03/25 18:01:11 +0000",
      "sharing": "public",
      "tag_list": "",
      "permalink": "been-a-jewel-stu-ku",
      "streamable": true,
      "embeddable_by": "all",
      "downloadable": false,
      "purchase_url": null,
      "label_id": null,
      "purchase_title": null,
      "genre": "Hip-hop & Rap",
      "title": "Been A Jewel - Stu-Ku",
      "description": "\"I've been a jewel, but it's hard to find a diamond in the rough\" - Stu-Ku",
      "label_name": null,
      "release": null,
      "track_type": null,
      "key_signature": null,
      "isrc": null,
      "video_url": null,
      "bpm": null,
      "release_year": null,
      "release_month": null,
      "release_day": null,
      "original_format": "mp3",
      "license": "all-rights-reserved",
      "uri": "https://api.soundcloud.com/tracks/419605204",
      "user": {
      "id": 277946511,
      "kind": "user",
      "permalink": "hugh-campbell-789707573",
      "username": "Hugh Campbell",
      "last_modified": "2018/02/05 03:35:02 +0000",
      "uri": "https://api.soundcloud.com/users/277946511",
      "permalink_url": "http://soundcloud.com/hugh-campbell-789707573",
      "avatar_url": "https://i1.sndcdn.com/avatars-000286123444-mqsbf4-large.jpg"
      },
      "attachments_uri": "https://api.soundcloud.com/tracks/419605204/attachments",
      "permalink_url": "http://soundcloud.com/hugh-campbell-789707573/been-a-jewel-stu-ku",
      "artwork_url": "https://i1.sndcdn.com/artworks-000324203108-q4qxxp-cool.jpg",
      "waveform_url": "https://w1.sndcdn.com/9DNkKDqe40bo_m.png",
      "stream_url": "https://api.soundcloud.com/tracks/419605204/stream",
      "playback_count": 0,
      "download_count": 0,
      "favoritings_count": 0,
      "comment_count": 0,
      "reposts_count": 0
      },
      {
      "kind": "track",
      "isPlaying": false,
      "id": 419605200,
      "created_at": "2018/03/25 18:01:09 +0000",
      "user_id": 391328688,
      "duration": 154553,
      "commentable": true,
      "state": "finished",
      "original_content_size": 27248312,
      "last_modified": "2018/03/25 18:01:11 +0000",
      "sharing": "public",
      "tag_list": "\"bedroom \" \"bedroom pop\" \"indie pop\" Acoustic lofi diy okc",
      "permalink": "light-blue",
      "streamable": true,
      "embeddable_by": "all",
      "downloadable": false,
      "purchase_url": null,
      "label_id": null,
      "purchase_title": null,
      "genre": "Pop",
      "title": "light blue",
      "description": "",
      "label_name": null,
      "release": null,
      "track_type": null,
      "key_signature": null,
      "isrc": null,
      "video_url": null,
      "bpm": null,
      "release_year": null,
      "release_month": null,
      "release_day": null,
      "original_format": "wav",
      "license": "all-rights-reserved",
      "uri": "https://api.soundcloud.com/tracks/419605200",
      "user": {
      "id": 391328688,
      "kind": "user",
      "permalink": "maryis",
      "username": "mary is",
      "last_modified": "2018/01/29 22:40:14 +0000",
      "uri": "https://api.soundcloud.com/users/391328688",
      "permalink_url": "http://soundcloud.com/maryis",
      "avatar_url": "https://i1.sndcdn.com/avatars-000391288605-rf61x7-large.jpg"
      },
      "attachments_uri": "https://api.soundcloud.com/tracks/419605200/attachments",
      "permalink_url": "http://soundcloud.com/maryis/light-blue",
      "artwork_url": "https://i1.sndcdn.com/artworks-000324203116-38iy5i-large.jpg",
      "waveform_url": "https://w1.sndcdn.com/eibCLHQt8C8n_m.png",
      "stream_url": "https://api.soundcloud.com/tracks/419605200/stream",
      "playback_count": 0,
      "download_count": 0,
      "favoritings_count": 0,
      "comment_count": 0,
      "reposts_count": 0
      },
      {
      "kind": "track",
      "isPlaying": false,
      "id": 419605196,
      "created_at": "2018/03/25 18:01:09 +0000",
      "user_id": 199306343,
      "duration": 102042,
      "commentable": true,
      "state": "finished",
      "original_content_size": 35979352,
      "last_modified": "2018/03/25 18:01:09 +0000",
      "sharing": "public",
      "tag_list": "",
      "permalink": "littlebrotherfacist",
      "streamable": true,
      "embeddable_by": "all",
      "downloadable": false,
      "purchase_url": null,
      "label_id": null,
      "purchase_title": null,
      "genre": "Electronic",
      "title": "LittleBrotherFacist",
      "description": "",
      "label_name": null,
      "release": null,
      "track_type": null,
      "key_signature": null,
      "isrc": null,
      "video_url": null,
      "bpm": null,
      "release_year": null,
      "release_month": null,
      "release_day": null,
      "original_format": "wav",
      "license": "all-rights-reserved",
      "uri": "https://api.soundcloud.com/tracks/419605196",
      "user": {
      "id": 199306343,
      "kind": "user",
      "permalink": "totallynotbcpunderassumesidentity",
      "username": "The Fabulous Keller Brothers",
      "last_modified": "2018/03/05 13:56:52 +0000",
      "uri": "https://api.soundcloud.com/users/199306343",
      "permalink_url": "http://soundcloud.com/totallynotbcpunderassumesidentity",
      "avatar_url": "https://i1.sndcdn.com/avatars-000407894076-dcfz8x-large.jpg"
      },
      "attachments_uri": "https://api.soundcloud.com/tracks/419605196/attachments",
      "permalink_url": "http://soundcloud.com/totallynotbcpunderassumesidentity/littlebrotherfacist",
      "artwork_url": null,
      "waveform_url": "https://w1.sndcdn.com/8VH1v86W259u_m.png",
      "stream_url": "https://api.soundcloud.com/tracks/419605196/stream",
      "playback_count": 0,
      "download_count": 0,
      "favoritings_count": 0,
      "comment_count": 0,
      "reposts_count": 0
      },
      {
      "kind": "track",
      "isPlaying": false,
      "id": 419605168,
      "created_at": "2018/03/25 18:01:04 +0000",
      "user_id": 20899123,
      "duration": 194133,
      "commentable": true,
      "state": "finished",
      "original_content_size": 7766643,
      "last_modified": "2018/03/25 18:01:04 +0000",
      "sharing": "public",
      "tag_list": "",
      "permalink": "transbay-chase",
      "streamable": true,
      "embeddable_by": "all",
      "downloadable": false,
      "purchase_url": null,
      "label_id": null,
      "purchase_title": null,
      "genre": "",
      "title": "Transbay Pursuit",
      "description": "Some new soundtrack work",
      "label_name": null,
      "release": null,
      "track_type": null,
      "key_signature": null,
      "isrc": null,
      "video_url": null,
      "bpm": null,
      "release_year": null,
      "release_month": null,
      "release_day": null,
      "original_format": "mp3",
      "license": "all-rights-reserved",
      "uri": "https://api.soundcloud.com/tracks/419605168",
      "user": {
      "id": 20899123,
      "kind": "user",
      "permalink": "lance-kunnath",
      "username": "DJ Lantz",
      "last_modified": "2018/03/04 22:10:44 +0000",
      "uri": "https://api.soundcloud.com/users/20899123",
      "permalink_url": "http://soundcloud.com/lance-kunnath",
      "avatar_url": "https://i1.sndcdn.com/avatars-000075026715-zrkp5i-large.jpg"
      },
      "attachments_uri": "https://api.soundcloud.com/tracks/419605168/attachments",
      "permalink_url": "http://soundcloud.com/lance-kunnath/transbay-chase",
      "artwork_url": null,
      "waveform_url": "https://w1.sndcdn.com/GSAgtadxxxtq_m.png",
      "stream_url": "https://api.soundcloud.com/tracks/419605168/stream",
      "playback_count": 0,
      "download_count": 0,
      "favoritings_count": 0,
      "comment_count": 0,
      "reposts_count": 0
      },
      {
      "kind": "track",
      "isPlaying": false,
      "id": 419605156,
      "created_at": "2018/03/25 18:01:04 +0000",
      "user_id": 380468477,
      "duration": 55959,
      "commentable": true,
      "state": "finished",
      "original_content_size": 941739,
      "last_modified": "2018/03/25 18:01:08 +0000",
      "sharing": "public",
      "tag_list": "soundcloud:source=android-3rdparty-upload",
      "permalink": "querido-deus",
      "streamable": true,
      "embeddable_by": "all",
      "downloadable": false,
      "purchase_url": null,
      "label_id": null,
      "purchase_title": null,
      "genre": null,
      "title": "Querido Deus",
      "description": null,
      "label_name": null,
      "release": null,
      "track_type": "recording",
      "key_signature": null,
      "isrc": null,
      "video_url": null,
      "bpm": null,
      "release_year": null,
      "release_month": null,
      "release_day": null,
      "original_format": "raw",
      "license": "all-rights-reserved",
      "uri": "https://api.soundcloud.com/tracks/419605156",
      "user": {
      "id": 380468477,
      "kind": "user",
      "permalink": "claudia-ribas-83548713",
      "username": "Claudia Ribas",
      "last_modified": "2018/03/25 17:50:21 +0000",
      "uri": "https://api.soundcloud.com/users/380468477",
      "permalink_url": "http://soundcloud.com/claudia-ribas-83548713",
      "avatar_url": "https://i1.sndcdn.com/avatars-000421995184-pr0k0j-large.jpg"
      },
      "attachments_uri": "https://api.soundcloud.com/tracks/419605156/attachments",
      "permalink_url": "http://soundcloud.com/claudia-ribas-83548713/querido-deus",
      "artwork_url": "https://i1.sndcdn.com/artworks-000324203044-uqaxe6-large.jpg",
      "waveform_url": "https://w1.sndcdn.com/cURFH9tNXPF4_m.png",
      "stream_url": "https://api.soundcloud.com/tracks/419605156/stream",
      "playback_count": 0,
      "download_count": 0,
      "favoritings_count": 0,
      "comment_count": 0,
      "reposts_count": 0
      },
      {
      "kind": "track",
      "isPlaying": false,
      "id": 419605136,
      "created_at": "2018/03/25 18:01:00 +0000",
      "user_id": 333691891,
      "duration": 157219,
      "commentable": true,
      "state": "finished",
      "original_content_size": 6288195,
      "last_modified": "2018/03/25 18:01:00 +0000",
      "sharing": "public",
      "tag_list": "",
      "permalink": "game-changer-official-audio-big-th3o",
      "streamable": true,
      "embeddable_by": "all",
      "downloadable": false,
      "purchase_url": null,
      "label_id": null,
      "purchase_title": null,
      "genre": "Hip-hop & Rap",
      "title": "Game Changer Official Audio - Big Th3o x SMG",
      "description": "Beat by ElevenEleven",
      "label_name": null,
      "release": null,
      "track_type": null,
      "key_signature": null,
      "isrc": null,
      "video_url": null,
      "bpm": null,
      "release_year": null,
      "release_month": null,
      "release_day": null,
      "original_format": "mp3",
      "license": "all-rights-reserved",
      "uri": "https://api.soundcloud.com/tracks/419605136",
      "user": {
      "id": 333691891,
      "kind": "user",
      "permalink": "lt-felder",
      "username": "BIG Th3o",
      "last_modified": "2018/02/26 19:00:16 +0000",
      "uri": "https://api.soundcloud.com/users/333691891",
      "permalink_url": "http://soundcloud.com/lt-felder",
      "avatar_url": "https://i1.sndcdn.com/avatars-000352687034-732ob6-large.jpg"
      },
      "attachments_uri": "https://api.soundcloud.com/tracks/419605136/attachments",
      "permalink_url": "http://soundcloud.com/lt-felder/game-changer-official-audio-big-th3o",
      "artwork_url": "https://i1.sndcdn.com/artworks-000324203004-rhjwps-large.jpg",
      "waveform_url": "https://w1.sndcdn.com/Z2ZelkPBKGwm_m.png",
      "stream_url": "https://api.soundcloud.com/tracks/419605136/stream",
      "playback_count": 0,
      "download_count": 0,
      "favoritings_count": 0,
      "comment_count": 0,
      "reposts_count": 0
      },
      {
      "kind": "track",
      "isPlaying": false,
      "id": 419605132,
      "created_at": "2018/03/25 18:00:59 +0000",
      "user_id": 71267758,
      "duration": 352346,
      "commentable": true,
      "state": "finished",
      "original_content_size": 11919557,
      "last_modified": "2018/03/25 18:01:04 +0000",
      "sharing": "public",
      "tag_list": "",
      "permalink": "intro",
      "streamable": true,
      "embeddable_by": "all",
      "downloadable": false,
      "purchase_url": null,
      "label_id": null,
      "purchase_title": null,
      "genre": "",
      "title": "Intro",
      "description": "Spitta x PrincessSpitta",
      "label_name": null,
      "release": null,
      "track_type": null,
      "key_signature": null,
      "isrc": null,
      "video_url": null,
      "bpm": null,
      "release_year": null,
      "release_month": null,
      "release_day": null,
      "original_format": "m4a",
      "license": "all-rights-reserved",
      "uri": "https://api.soundcloud.com/tracks/419605132",
      "user": {
      "id": 71267758,
      "kind": "user",
      "permalink": "torrell-spitta-ingram",
      "username": "Official Spitta",
      "last_modified": "2018/03/12 06:16:51 +0000",
      "uri": "https://api.soundcloud.com/users/71267758",
      "permalink_url": "http://soundcloud.com/torrell-spitta-ingram",
      "avatar_url": "https://i1.sndcdn.com/avatars-000414384471-2dm05x-large.jpg"
      },
      "attachments_uri": "https://api.soundcloud.com/tracks/419605132/attachments",
      "permalink_url": "http://soundcloud.com/torrell-spitta-ingram/intro",
      "artwork_url": "https://i1.sndcdn.com/artworks-000324203036-qjwrwu-large.jpg",
      "waveform_url": "https://w1.sndcdn.com/PRTVTJvD5ieq_m.png",
      "stream_url": "https://api.soundcloud.com/tracks/419605132/stream",
      "playback_count": 0,
      "download_count": 0,
      "favoritings_count": 0,
      "comment_count": 0,
      "reposts_count": 0
      },
      {
      "kind": "track",
      "isPlaying": false,
      "id": 419605116,
      "created_at": "2018/03/25 18:00:59 +0000",
      "user_id": 15266105,
      "duration": 132949,
      "commentable": true,
      "state": "finished",
      "original_content_size": 3193334,
      "last_modified": "2018/03/25 18:01:01 +0000",
      "sharing": "public",
      "tag_list": "sounday hurryguap vengo trap drill lombardrill",
      "permalink": "vendo-freestyleprod-by-hurry-guap-sounday-7",
      "streamable": true,
      "embeddable_by": "all",
      "downloadable": true,
      "purchase_url": null,
      "label_id": null,
      "purchase_title": null,
      "genre": "Trap",
      "title": "Vendo (freestyle)(prod. by Hurry Guap) SOUNDAY #7",
      "description": "",
      "label_name": null,
      "release": null,
      "track_type": null,
      "key_signature": null,
      "isrc": null,
      "video_url": null,
      "bpm": null,
      "release_year": null,
      "release_month": null,
      "release_day": null,
      "original_format": "mp3",
      "license": "all-rights-reserved",
      "uri": "https://api.soundcloud.com/tracks/419605116",
      "user": {
      "id": 15266105,
      "kind": "user",
      "permalink": "hurryguapblackerrything",
      "username": "Hurry Guap",
      "last_modified": "2018/02/12 18:59:01 +0000",
      "uri": "https://api.soundcloud.com/users/15266105",
      "permalink_url": "http://soundcloud.com/hurryguapblackerrything",
      "avatar_url": "https://i1.sndcdn.com/avatars-000396624621-wz8uw9-large.jpg"
      },
      "attachments_uri": "https://api.soundcloud.com/tracks/419605116/attachments",
      "permalink_url": "http://soundcloud.com/hurryguapblackerrything/vendo-freestyleprod-by-hurry-guap-sounday-7",
      "artwork_url": "https://i1.sndcdn.com/artworks-000324203008-y71h5i-large.jpg",
      "waveform_url": "https://w1.sndcdn.com/9tORdn9Wvnwo_m.png",
      "stream_url": "https://api.soundcloud.com/tracks/419605116/stream",
      "download_url": "https://api.soundcloud.com/tracks/419605116/download",
      "playback_count": 1,
      "download_count": 0,
      "favoritings_count": 0,
      "comment_count": 0,
      "reposts_count": 0
      },
      {
      "kind": "track",
      "isPlaying": false,
      "id": 419605064,
      "created_at": "2018/03/25 18:00:54 +0000",
      "user_id": 91484992,
      "duration": 335102,
      "commentable": true,
      "state": "finished",
      "original_content_size": 59097570,
      "last_modified": "2018/03/25 18:00:54 +0000",
      "sharing": "public",
      "tag_list": "UTAU",
      "permalink": "alternative-voice-demo-eat-me-utau",
      "streamable": true,
      "embeddable_by": "all",
      "downloadable": false,
      "purchase_url": null,
      "label_id": null,
      "purchase_title": null,
      "genre": "",
      "title": "Alternative Voice DEMO - EAT ME | UTAUカバー",
      "description": "This is one of 3 release covers, 1 to go.\n\nThis cover uses her vocal frys and breaths, moresampler with no Mt flags. I wanted to show how her voice sounds without Mt, this cover uses Mt flags, if you are interested https://soundcloud.com/catlione/alternative-voice-demo-utau\n\nNew Alternative Voice's VB is 3 pitch, fully rerecorded, comes with a base set of vocal fry and glotal stops. Her new concept is to follow the same pitch map for every voicebank I'm gonna to realease in a future.\n\nThere is no new illustration yet, so I'm using old one orz\n\noriginal by OSTER project\nust by Kream, fully tuned by me. I used Kuyuri's cover to mimic pitchbends.",
      "label_name": null,
      "release": null,
      "track_type": null,
      "key_signature": null,
      "isrc": null,
      "video_url": null,
      "bpm": null,
      "release_year": null,
      "release_month": null,
      "release_day": null,
      "original_format": "wav",
      "license": "all-rights-reserved",
      "uri": "https://api.soundcloud.com/tracks/419605064",
      "user": {
      "id": 91484992,
      "kind": "user",
      "permalink": "catlione",
      "username": "Catlione ★ UTAU CV→VCV",
      "last_modified": "2017/04/07 06:08:01 +0000",
      "uri": "https://api.soundcloud.com/users/91484992",
      "permalink_url": "http://soundcloud.com/catlione",
      "avatar_url": "https://i1.sndcdn.com/avatars-000303549741-hwac4g-large.jpg"
      },
      "attachments_uri": "https://api.soundcloud.com/tracks/419605064/attachments",
      "permalink_url": "http://soundcloud.com/catlione/alternative-voice-demo-eat-me-utau",
      "artwork_url": "https://i1.sndcdn.com/artworks-000324202976-wrrfmh-large.jpg",
      "waveform_url": "https://w1.sndcdn.com/b48Wa91yEKJi_m.png",
      "stream_url": "https://api.soundcloud.com/tracks/419605064/stream",
      "playback_count": 0,
      "download_count": 0,
      "favoritings_count": 0,
      "comment_count": 0,
      "reposts_count": 0
      },
      {
      "kind": "track",
      "isPlaying": false,
      "id": 419605048,
      "created_at": "2018/03/25 18:00:52 +0000",
      "user_id": 189406296,
      "duration": 245756,
      "commentable": true,
      "state": "finished",
      "original_content_size": 9827335,
      "last_modified": "2018/03/25 18:00:53 +0000",
      "sharing": "public",
      "tag_list": "\"bigroom break\" EDM \"wubz \" Madness",
      "permalink": "madness",
      "streamable": true,
      "embeddable_by": "all",
      "downloadable": false,
      "purchase_url": null,
      "label_id": null,
      "purchase_title": null,
      "genre": "Dance & EDM",
      "title": "Madness",
      "description": "New big room track in honor of festivals season.",
      "label_name": null,
      "release": null,
      "track_type": null,
      "key_signature": null,
      "isrc": null,
      "video_url": null,
      "bpm": null,
      "release_year": null,
      "release_month": null,
      "release_day": null,
      "original_format": "mp3",
      "license": "all-rights-reserved",
      "uri": "https://api.soundcloud.com/tracks/419605048",
      "user": {
      "id": 189406296,
      "kind": "user",
      "permalink": "sentrexmusic",
      "username": "Sentr3x",
      "last_modified": "2018/03/12 21:13:24 +0000",
      "uri": "https://api.soundcloud.com/users/189406296",
      "permalink_url": "http://soundcloud.com/sentrexmusic",
      "avatar_url": "https://i1.sndcdn.com/avatars-000385273265-havvk0-large.jpg"
      },
      "attachments_uri": "https://api.soundcloud.com/tracks/419605048/attachments",
      "permalink_url": "http://soundcloud.com/sentrexmusic/madness",
      "artwork_url": "https://i1.sndcdn.com/artworks-000324202948-r6oz3k-large.jpg",
      "waveform_url": "https://w1.sndcdn.com/8b4P3Bp1pE5d_m.png",
      "stream_url": "https://api.soundcloud.com/tracks/419605048/stream",
      "playback_count": 0,
      "download_count": 0,
      "favoritings_count": 0,
      "comment_count": 0,
      "reposts_count": 0
      },
      {
      "kind": "track",
      "isPlaying": false,
      "id": 419605040,
      "created_at": "2018/03/25 18:00:51 +0000",
      "user_id": 49434144,
      "duration": 252079,
      "commentable": true,
      "state": "finished",
      "original_content_size": 96768044,
      "last_modified": "2018/03/25 18:00:52 +0000",
      "sharing": "public",
      "tag_list": "modular Synthesizer Synth Music",
      "permalink": "sub-systems",
      "streamable": true,
      "embeddable_by": "all",
      "downloadable": false,
      "purchase_url": null,
      "label_id": null,
      "purchase_title": null,
      "genre": "SUB SYSTEMS",
      "title": "SUB SYSTEMS - ***",
      "description": "",
      "label_name": null,
      "release": null,
      "track_type": null,
      "key_signature": null,
      "isrc": null,
      "video_url": null,
      "bpm": null,
      "release_year": null,
      "release_month": null,
      "release_day": null,
      "original_format": "wav",
      "license": "all-rights-reserved",
      "uri": "https://api.soundcloud.com/tracks/419605040",
      "user": {
      "id": 49434144,
      "kind": "user",
      "permalink": "sub-systems",
      "username": "SUB SYSTEMS",
      "last_modified": "2018/03/15 22:33:12 +0000",
      "uri": "https://api.soundcloud.com/users/49434144",
      "permalink_url": "http://soundcloud.com/sub-systems",
      "avatar_url": "https://i1.sndcdn.com/avatars-000198525574-lqel20-large.jpg"
      },
      "attachments_uri": "https://api.soundcloud.com/tracks/419605040/attachments",
      "permalink_url": "http://soundcloud.com/sub-systems/sub-systems",
      "artwork_url": "https://i1.sndcdn.com/artworks-000324202932-n4c3ft-large.jpg",
      "waveform_url": "https://w1.sndcdn.com/d0mFkot56XjP_m.png",
      "stream_url": "https://api.soundcloud.com/tracks/419605040/stream",
      "playback_count": 1,
      "download_count": 0,
      "favoritings_count": 0,
      "comment_count": 0,
      "reposts_count": 0
      },
      {
      "kind": "track",
      "isPlaying": false,
      "id": 419605036,
      "created_at": "2018/03/25 18:00:50 +0000",
      "user_id": 292279788,
      "duration": 183370,
      "commentable": true,
      "state": "finished",
      "original_content_size": 7332119,
      "last_modified": "2018/03/25 18:01:02 +0000",
      "sharing": "public",
      "tag_list": "",
      "permalink": "feder-goodbye-feat-lyse-daniele-n-rmx",
      "streamable": true,
      "embeddable_by": "all",
      "downloadable": false,
      "purchase_url": null,
      "label_id": null,
      "purchase_title": null,
      "genre": "Dance e EDM",
      "title": "Feder - Goodbye Feat. Lyse (Daniele N RMX)",
      "description": "",
      "label_name": null,
      "release": null,
      "track_type": null,
      "key_signature": null,
      "isrc": null,
      "video_url": null,
      "bpm": null,
      "release_year": null,
      "release_month": null,
      "release_day": null,
      "original_format": "mp3",
      "license": "all-rights-reserved",
      "uri": "https://api.soundcloud.com/tracks/419605036",
      "user": {
      "id": 292279788,
      "kind": "user",
      "permalink": "daniele-n-958529307",
      "username": "DJ Daniele N",
      "last_modified": "2018/03/22 18:00:33 +0000",
      "uri": "https://api.soundcloud.com/users/292279788",
      "permalink_url": "http://soundcloud.com/daniele-n-958529307",
      "avatar_url": "https://i1.sndcdn.com/avatars-000337908135-nv8nx4-large.jpg"
      },
      "attachments_uri": "https://api.soundcloud.com/tracks/419605036/attachments",
      "permalink_url": "http://soundcloud.com/daniele-n-958529307/feder-goodbye-feat-lyse-daniele-n-rmx",
      "artwork_url": "https://i1.sndcdn.com/artworks-000324202924-g1blhk-large.jpg",
      "waveform_url": "https://w1.sndcdn.com/JkVK7AOVEepR_m.png",
      "stream_url": "https://api.soundcloud.com/tracks/419605036/stream",
      "playback_count": 0,
      "download_count": 0,
      "favoritings_count": 0,
      "comment_count": 0,
      "reposts_count": 0
      },
      {
      "kind": "track",
      "isPlaying": false,
      "id": 419605016,
      "created_at": "2018/03/25 18:00:49 +0000",
      "user_id": 416160765,
      "duration": 188046,
      "commentable": true,
      "state": "finished",
      "original_content_size": 1682327,
      "last_modified": "2018/03/25 18:00:58 +0000",
      "sharing": "public",
      "tag_list": "soundcloud:source=android-record",
      "permalink": "mar-23-2018",
      "streamable": true,
      "embeddable_by": "all",
      "downloadable": false,
      "purchase_url": null,
      "label_id": null,
      "purchase_title": null,
      "genre": null,
      "title": "Mar 23,2018",
      "description": null,
      "label_name": null,
      "release": null,
      "track_type": "recording",
      "key_signature": null,
      "isrc": null,
      "video_url": null,
      "bpm": null,
      "release_year": null,
      "release_month": null,
      "release_day": null,
      "original_format": "ogg",
      "license": "all-rights-reserved",
      "uri": "https://api.soundcloud.com/tracks/419605016",
      "user": {
      "id": 416160765,
      "kind": "user",
      "permalink": "tr-n-kim-nh-161926149",
      "username": "Trần Kim Như",
      "last_modified": "2018/03/14 17:00:43 +0000",
      "uri": "https://api.soundcloud.com/users/416160765",
      "permalink_url": "http://soundcloud.com/tr-n-kim-nh-161926149",
      "avatar_url": "https://i1.sndcdn.com/avatars-000415802298-jv4bes-large.jpg"
      },
      "attachments_uri": "https://api.soundcloud.com/tracks/419605016/attachments",
      "permalink_url": "http://soundcloud.com/tr-n-kim-nh-161926149/mar-23-2018",
      "artwork_url": null,
      "waveform_url": "https://w1.sndcdn.com/cpvEN8Ua56Wi_m.png",
      "stream_url": "https://api.soundcloud.com/tracks/419605016/stream",
      "playback_count": 0,
      "download_count": 0,
      "favoritings_count": 0,
      "comment_count": 0,
      "reposts_count": 0
      },
      {
      "kind": "track",
      "isPlaying": false,
      "id": 419605008,
      "created_at": "2018/03/25 18:00:48 +0000",
      "user_id": 344221100,
      "duration": 139793,
      "commentable": true,
      "state": "finished",
      "original_content_size": 1703279,
      "last_modified": "2018/03/25 18:00:56 +0000",
      "sharing": "public",
      "tag_list": "soundcloud:source=android-3rdparty-upload",
      "permalink": "sheadatear",
      "streamable": true,
      "embeddable_by": "all",
      "downloadable": false,
      "purchase_url": null,
      "label_id": null,
      "purchase_title": null,
      "genre": null,
      "title": "SheadATear",
      "description": null,
      "label_name": null,
      "release": null,
      "track_type": "recording",
      "key_signature": null,
      "isrc": null,
      "video_url": null,
      "bpm": null,
      "release_year": null,
      "release_month": null,
      "release_day": null,
      "original_format": "m4a",
      "license": "all-rights-reserved",
      "uri": "https://api.soundcloud.com/tracks/419605008",
      "user": {
      "id": 344221100,
      "kind": "user",
      "permalink": "user-627645055",
      "username": "K.WELL",
      "last_modified": "2018/01/10 10:39:56 +0000",
      "uri": "https://api.soundcloud.com/users/344221100",
      "permalink_url": "http://soundcloud.com/user-627645055",
      "avatar_url": "https://i1.sndcdn.com/avatars-000345693089-gj6gmc-large.jpg"
      },
      "attachments_uri": "https://api.soundcloud.com/tracks/419605008/attachments",
      "permalink_url": "http://soundcloud.com/user-627645055/sheadatear",
      "artwork_url": "https://i1.sndcdn.com/artworks-000324202892-pez6tt-large.jpg",
      "waveform_url": "https://w1.sndcdn.com/beLaVj3HHYxu_m.png",
      "stream_url": "https://api.soundcloud.com/tracks/419605008/stream",
      "playback_count": 0,
      "download_count": 0,
      "favoritings_count": 0,
      "comment_count": 0,
      "reposts_count": 0
      },
      {
      "kind": "track",
      "isPlaying": false,
      "id": 419605004,
      "created_at": "2018/03/25 18:00:48 +0000",
      "user_id": 12872745,
      "duration": 243170,
      "commentable": true,
      "state": "finished",
      "original_content_size": 5835545,
      "last_modified": "2018/03/25 18:00:48 +0000",
      "sharing": "public",
      "tag_list": "\"rant step\" Blowzabella",
      "permalink": "falco",
      "streamable": true,
      "embeddable_by": "all",
      "downloadable": false,
      "purchase_url": null,
      "label_id": null,
      "purchase_title": null,
      "genre": "World",
      "title": "Falco",
      "description": "Une rant step dance écrite par Paul James, de Blowzabella.\nA rant step dance written by Paul James of Blowzabella.",
      "label_name": null,
      "release": null,
      "track_type": null,
      "key_signature": null,
      "isrc": null,
      "video_url": null,
      "bpm": null,
      "release_year": null,
      "release_month": null,
      "release_day": null,
      "original_format": "mp3",
      "license": "all-rights-reserved",
      "uri": "https://api.soundcloud.com/tracks/419605004",
      "user": {
      "id": 12872745,
      "kind": "user",
      "permalink": "daniel-marchand",
      "username": "Daniel Marchand",
      "last_modified": "2016/11/13 08:37:40 +0000",
      "uri": "https://api.soundcloud.com/users/12872745",
      "permalink_url": "http://soundcloud.com/daniel-marchand",
      "avatar_url": "https://i1.sndcdn.com/avatars-000011098061-93oit8-large.jpg"
      },
      "attachments_uri": "https://api.soundcloud.com/tracks/419605004/attachments",
      "permalink_url": "http://soundcloud.com/daniel-marchand/falco",
      "artwork_url": null,
      "waveform_url": "https://w1.sndcdn.com/UVNNnzXGhqd6_m.png",
      "stream_url": "https://api.soundcloud.com/tracks/419605004/stream",
      "playback_count": 0,
      "download_count": 0,
      "favoritings_count": 0,
      "comment_count": 0,
      "reposts_count": 0
      },
      {
      "kind": "track",
      "isPlaying": false,
      "id": 419604992,
      "created_at": "2018/03/25 18:00:45 +0000",
      "user_id": 422919864,
      "duration": 88301,
      "commentable": true,
      "state": "finished",
      "original_content_size": 1415884,
      "last_modified": "2018/03/25 18:00:48 +0000",
      "sharing": "public",
      "tag_list": "\"Vocal Group\" \"Australian Music\" \"Three Part Harmony\"",
      "permalink": "land-down-under",
      "streamable": true,
      "embeddable_by": "all",
      "downloadable": false,
      "purchase_url": null,
      "label_id": null,
      "purchase_title": null,
      "genre": "Vocal Group",
      "title": "Land Down Under",
      "description": "Arranged by Neil Rutherford for The Girls From Oz Group",
      "label_name": null,
      "release": null,
      "track_type": null,
      "key_signature": null,
      "isrc": null,
      "video_url": null,
      "bpm": null,
      "release_year": null,
      "release_month": null,
      "release_day": null,
      "original_format": "mp3",
      "license": "all-rights-reserved",
      "uri": "https://api.soundcloud.com/tracks/419604992",
      "user": {
      "id": 422919864,
      "kind": "user",
      "permalink": "user-906717723",
      "username": "The Girls From Oz",
      "last_modified": "2018/03/25 17:53:57 +0000",
      "uri": "https://api.soundcloud.com/users/422919864",
      "permalink_url": "http://soundcloud.com/user-906717723",
      "avatar_url": "https://i1.sndcdn.com/avatars-000422403900-gjm0gx-large.jpg"
      },
      "attachments_uri": "https://api.soundcloud.com/tracks/419604992/attachments",
      "permalink_url": "http://soundcloud.com/user-906717723/land-down-under",
      "artwork_url": "https://i1.sndcdn.com/artworks-000324202884-iyiaxs-large.jpg",
      "waveform_url": "https://w1.sndcdn.com/uCd3m5RjPoU8_m.png",
      "stream_url": "https://api.soundcloud.com/tracks/419604992/stream",
      "playback_count": 0,
      "download_count": 0,
      "favoritings_count": 0,
      "comment_count": 0,
      "reposts_count": 0
      },
      {
      "kind": "track",
      "isPlaying": false,
      "id": 419604988,
      "created_at": "2018/03/25 18:00:45 +0000",
      "user_id": 12872745,
      "duration": 355690,
      "commentable": true,
      "state": "finished",
      "original_content_size": 8535770,
      "last_modified": "2018/03/25 18:00:45 +0000",
      "sharing": "public",
      "tag_list": "cercle circassien \"cercle circassien\" circle \"circassian circle\"",
      "permalink": "la-marmotte-jump-at-the-sun",
      "streamable": true,
      "embeddable_by": "all",
      "downloadable": false,
      "purchase_url": null,
      "label_id": null,
      "purchase_title": null,
      "genre": "",
      "title": "La Marmotte Jump At The Sun",
      "description": "2 cercles circassiens : La marmotte : trad Savoie et Jump at the sun écrit par John Kirkpatrick\n2 circassian circles  : La marmotte : trad from Savoie (France) and Jump at the sun written by John Kirkpatrick",
      "label_name": null,
      "release": null,
      "track_type": null,
      "key_signature": null,
      "isrc": null,
      "video_url": null,
      "bpm": null,
      "release_year": null,
      "release_month": null,
      "release_day": null,
      "original_format": "mp3",
      "license": "all-rights-reserved",
      "uri": "https://api.soundcloud.com/tracks/419604988",
      "user": {
      "id": 12872745,
      "kind": "user",
      "permalink": "daniel-marchand",
      "username": "Daniel Marchand",
      "last_modified": "2016/11/13 08:37:40 +0000",
      "uri": "https://api.soundcloud.com/users/12872745",
      "permalink_url": "http://soundcloud.com/daniel-marchand",
      "avatar_url": "https://i1.sndcdn.com/avatars-000011098061-93oit8-large.jpg"
      },
      "attachments_uri": "https://api.soundcloud.com/tracks/419604988/attachments",
      "permalink_url": "http://soundcloud.com/daniel-marchand/la-marmotte-jump-at-the-sun",
      "artwork_url": null,
      "waveform_url": "https://w1.sndcdn.com/CT9xhOPMjsL9_m.png",
      "stream_url": "https://api.soundcloud.com/tracks/419604988/stream",
      "playback_count": 0,
      "download_count": 0,
      "favoritings_count": 0,
      "comment_count": 0,
      "reposts_count": 0
      },
      {
      "kind": "track",
      "isPlaying": false,
      "id": 419604984,
      "created_at": "2018/03/25 18:00:45 +0000",
      "user_id": 419636412,
      "duration": 96713,
      "commentable": true,
      "state": "finished",
      "original_content_size": 3009396,
      "last_modified": "2018/03/25 18:00:56 +0000",
      "sharing": "public",
      "tag_list": "freestyle bars beats rap hiphop %@ SOB Production",
      "permalink": "lil-daim-haters-bars-gang-lit",
      "streamable": true,
      "embeddable_by": "all",
      "downloadable": false,
      "purchase_url": null,
      "label_id": null,
      "purchase_title": null,
      "genre": "rapchat",
      "title": "Lil daim #haters  #BARS  #GANG   #lit #💯🔥🙏  via the Rapchat app (prod. by SOB Production)",
      "description": null,
      "label_name": null,
      "release": null,
      "track_type": null,
      "key_signature": null,
      "isrc": null,
      "video_url": null,
      "bpm": null,
      "release_year": null,
      "release_month": null,
      "release_day": null,
      "original_format": "m4a",
      "license": "all-rights-reserved",
      "uri": "https://api.soundcloud.com/tracks/419604984",
      "user": {
      "id": 419636412,
      "kind": "user",
      "permalink": "lil_daim",
      "username": "Lil daim",
      "last_modified": "2018/03/21 23:32:11 +0000",
      "uri": "https://api.soundcloud.com/users/419636412",
      "permalink_url": "http://soundcloud.com/lil_daim",
      "avatar_url": "https://i1.sndcdn.com/avatars-000419199249-hyqx55-large.jpg"
      },
      "attachments_uri": "https://api.soundcloud.com/tracks/419604984/attachments",
      "permalink_url": "http://soundcloud.com/lil_daim/lil-daim-haters-bars-gang-lit",
      "artwork_url": "https://i1.sndcdn.com/artworks-000324202856-x06k04-large.jpg",
      "waveform_url": "https://w1.sndcdn.com/Lmw9ZyFnMZi2_m.png",
      "stream_url": "https://api.soundcloud.com/tracks/419604984/stream",
      "playback_count": 0,
      "download_count": 0,
      "favoritings_count": 0,
      "comment_count": 0,
      "reposts_count": 0
      },
      {
      "kind": "track",
      "isPlaying": false,
      "id": 419604972,
      "created_at": "2018/03/25 18:00:43 +0000",
      "user_id": 19221044,
      "duration": 215896,
      "commentable": true,
      "state": "finished",
      "original_content_size": 4946673,
      "last_modified": "2018/03/25 18:00:44 +0000",
      "sharing": "public",
      "tag_list": "Hip-Hop",
      "permalink": "remember-the-daze",
      "streamable": true,
      "embeddable_by": "all",
      "downloadable": true,
      "purchase_url": null,
      "label_id": null,
      "purchase_title": null,
      "genre": "Hip-hop & Rap",
      "title": "Remember The Daze",
      "description": "#RememberTheDaze",
      "label_name": null,
      "release": null,
      "track_type": null,
      "key_signature": null,
      "isrc": null,
      "video_url": null,
      "bpm": null,
      "release_year": null,
      "release_month": null,
      "release_day": null,
      "original_format": "mp3",
      "license": "all-rights-reserved",
      "uri": "https://api.soundcloud.com/tracks/419604972",
      "user": {
      "id": 19221044,
      "kind": "user",
      "permalink": "oyvmusik",
      "username": "oyvmusik",
      "last_modified": "2018/03/23 06:08:06 +0000",
      "uri": "https://api.soundcloud.com/users/19221044",
      "permalink_url": "http://soundcloud.com/oyvmusik",
      "avatar_url": "https://i1.sndcdn.com/avatars-000420606280-2jjr9q-large.jpg"
      },
      "attachments_uri": "https://api.soundcloud.com/tracks/419604972/attachments",
      "permalink_url": "http://soundcloud.com/oyvmusik/remember-the-daze",
      "artwork_url": "https://i1.sndcdn.com/artworks-000324202852-ck1cn0-large.jpg",
      "waveform_url": "https://w1.sndcdn.com/PqtvvbWtoTMf_m.png",
      "stream_url": "https://api.soundcloud.com/tracks/419604972/stream",
      "download_url": "https://api.soundcloud.com/tracks/419604972/download",
      "playback_count": 0,
      "download_count": 0,
      "favoritings_count": 0,
      "comment_count": 0,
      "reposts_count": 0
      },
      {
      "kind": "track",
      "isPlaying": false,
      "id": 419604968,
      "created_at": "2018/03/25 18:00:41 +0000",
      "user_id": 54491663,
      "duration": 22989,
      "commentable": true,
      "state": "finished",
      "original_content_size": 191402,
      "last_modified": "2018/03/25 18:00:42 +0000",
      "sharing": "public",
      "tag_list": "",
      "permalink": "charlotte-steiger-20-on-marching-for-change",
      "streamable": true,
      "embeddable_by": "all",
      "downloadable": false,
      "purchase_url": null,
      "label_id": null,
      "purchase_title": null,
      "genre": "",
      "title": "Charlotte Steiger '20 On Marching For Change",
      "description": "",
      "label_name": null,
      "release": null,
      "track_type": null,
      "key_signature": null,
      "isrc": null,
      "video_url": null,
      "bpm": null,
      "release_year": null,
      "release_month": null,
      "release_day": null,
      "original_format": "m4a",
      "license": "all-rights-reserved",
      "uri": "https://api.soundcloud.com/tracks/419604968",
      "user": {
      "id": 54491663,
      "kind": "user",
      "permalink": "foothill-dragon-press",
      "username": "Foothill Dragon Press",
      "last_modified": "2017/10/13 16:44:21 +0000",
      "uri": "https://api.soundcloud.com/users/54491663",
      "permalink_url": "http://soundcloud.com/foothill-dragon-press",
      "avatar_url": "https://i1.sndcdn.com/avatars-000170420442-mqjtos-large.jpg"
      },
      "attachments_uri": "https://api.soundcloud.com/tracks/419604968/attachments",
      "permalink_url": "http://soundcloud.com/foothill-dragon-press/charlotte-steiger-20-on-marching-for-change",
      "artwork_url": null,
      "waveform_url": "https://w1.sndcdn.com/ip9KD1aRKN8l_m.png",
      "stream_url": "https://api.soundcloud.com/tracks/419604968/stream",
      "playback_count": 0,
      "download_count": 0,
      "favoritings_count": 0,
      "comment_count": 0,
      "reposts_count": 0
      }
    ],
    playlist: {
      title: 'Current Playlist',
      tracks: []
    },
    options: {
      limit: 10,
      kind: 'trending'
    }
  },
  
  mutations: {
    setCurrentTrack: (state, selectedTrack) => {
      state.tracklist.forEach(track => {
        track == selectedTrack && track.isPlaying == false ? track.isPlaying = true : track.isPlaying = false;
      });

      return state.currentTrack == selectedTrack;
    },

    optimizeTrackImages: state => {
      return state.tracklist.forEach(track => {        
        if (track.artwork_url === null) {
          track.artwork_url = track.user.avatar_url.replace('large', 't500x500');
        } else {
          track.artwork_url = track.artwork_url.replace('large', 't500x500');
        }

        return track.artwork_url;
      });
    }
  }
});